"""empty message

Revision ID: 83fe8f930c57
Revises: e5e3ffd20b88
Create Date: 2022-07-05 15:34:10.133512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83fe8f930c57'
down_revision = 'e5e3ffd20b88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_doctors', 'password',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('user_doctors', 'sub_specialty',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_doctors', 'sub_specialty',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user_doctors', 'password',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###
