"""empty message

Revision ID: 8b1b78ee3f3c
Revises: add03d48ddba
Create Date: 2022-07-25 15:09:30.498716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b1b78ee3f3c'
down_revision = 'add03d48ddba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_doctors', 'image_profile',
               existing_type=sa.VARCHAR(length=520),
               nullable=True)
    op.drop_constraint('user_doctors_image_profile_key', 'user_doctors', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_doctors_image_profile_key', 'user_doctors', ['image_profile'])
    op.alter_column('user_doctors', 'image_profile',
               existing_type=sa.VARCHAR(length=520),
               nullable=False)
    # ### end Alembic commands ###
