"""empty message

Revision ID: 9a7a7baee3b7
Revises: f50ebded397e
Create Date: 2022-06-28 14:42:58.997924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a7a7baee3b7'
down_revision = 'f50ebded397e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_doctors', sa.Column('specialty', sa.String(length=120), nullable=False))
    op.add_column('user_doctors', sa.Column('sub_specialty', sa.String(length=120), nullable=False))
    op.add_column('user_doctors', sa.Column('years_of_experience', sa.Integer(), nullable=True))
    op.add_column('user_doctors', sa.Column('aboutme', sa.String(length=520), nullable=True))
    op.add_column('user_doctors', sa.Column('howicanhelp', sa.String(length=520), nullable=True))
    op.add_column('user_doctors', sa.Column('services', sa.String(length=520), nullable=True))
    op.add_column('user_doctors', sa.Column('certifications', sa.String(length=520), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_doctors', 'certifications')
    op.drop_column('user_doctors', 'services')
    op.drop_column('user_doctors', 'howicanhelp')
    op.drop_column('user_doctors', 'aboutme')
    op.drop_column('user_doctors', 'years_of_experience')
    op.drop_column('user_doctors', 'sub_specialty')
    op.drop_column('user_doctors', 'specialty')
    # ### end Alembic commands ###
