"""empty message

Revision ID: b17a03f0d321
Revises: 13dd3914e8d9
Create Date: 2022-05-30 13:57:01.388169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b17a03f0d321'
down_revision = '13dd3914e8d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('aboutme', sa.String(length=520), nullable=True),
    sa.Column('howicanhelp', sa.String(length=520), nullable=True),
    sa.Column('services', sa.String(length=520), nullable=True),
    sa.Column('certifications', sa.String(length=520), nullable=True),
    sa.Column('comments', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe')
    # ### end Alembic commands ###
