"""empty message

Revision ID: c694ced3e460
Revises: bf6d87425da6
Create Date: 2022-07-05 15:41:07.484292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c694ced3e460'
down_revision = 'bf6d87425da6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_doctors_email_key', 'user_doctors', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_doctors_email_key', 'user_doctors', ['email'])
    # ### end Alembic commands ###
